# Generated by Django 4.1.5 on 2023-01-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="command",
            name="usr",
        ),
        migrations.AlterField(
            model_name="command",
            name="cmd",
            field=models.TextField(),
        ),
    ]
