# Generated by Django 4.1.5 on 2023-01-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_command_usr_alter_command_cmd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="command",
            name="cmd",
            field=models.TextField(null=True),
        ),
    ]
